--- #YAML:1.0
name:               Archive-Peek
version:            0.35
abstract:           Peek into archives without extracting them
author:
    - Leon Brocard <acme@astray.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Tar:         0
    Archive::Zip:         0
    Moose:                0
    MooseX::Types::Path::Class:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
